{% set name = "mne-features" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cae131cf167d092ce37fabda2ed0d7c0d083f02f58fffc15ba1526aca1e393aa

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy >=1.17
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - matplotlib-base >=1.5
    - scipy >=1.0
    - numba >=0.46.0
    - llvmlite >=0.30
    - scikit-learn >=0.21
    - mne-base >=0.18.2
    - pywavelets >=0.5.2
    - pandas >=0.25

test:
  imports:
    - mne_features
    - mne_features.feature_extraction
    - mne_features.univariate
    - mne_features.utils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://mne.tools/mne-features
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Software for extracting features from multivariate time series data
  dev_url: https://github.com/mne-tools/mne-features

extra:
  recipe-maintainers:
    - hoechenberger
    - larsoner
